version: "3"

services:
  mongodb:
    image: bitnami/mongodb:5.0.18
    restart: unless-stopped
    container_name: "mongodb"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_DATABASE=shoppik
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=rootuser
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./apps/api/data/mongo:/bitnami/mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7.2-rc2-alpine
    container_name: "redis"
    volumes:
      - ./apps/api/data/redis:/data
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

volumes:
  mongodb: null
  # bullmq:
  #     driver: bridge
