version: "3"

services:
  api:
    # image: veneno:latest
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - API_PORT=9000
      - API_HOST=${API_HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: bitnami/mongodb:5.0.18
    restart: unless-stopped
    container_name: "mongodb"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_ROOT_USER=rootuser
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_DATABASE=shoppik
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./apps/api/data/mongo:/bitnami/mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0.9-alpine
    container_name: "redis"
    volumes:
      - ./apps/api/data/redis:/data
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 6s

volumes:
  mongodb: null
  # bullmq:
  #     driver: bridge
