version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - API_PORT=9000
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - DATABASE_URL=${DATABASE_URL}
      - APP_ENV=${APP_ENV}
      - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
      - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      # - mongodb
      - redis

  # mongodb:
  #   image: bitnami/mongodb:5.0.18
  #   restart: unless-stopped
  #   container_name: "mongodb"
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
  #     - MONGODB_ROOT_USER=rootuser
  #     - MONGODB_ROOT_PASSWORD=rootpassword
  #     - MONGODB_DATABASE=shoppik
  #     - MONGODB_REPLICA_SET_MODE=primary
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #   volumes:
  #     - ./apps/api/data/mongo:/bitnami/mongodb
  #   ports:
  #     - "27017:27017"

  # redis:
  #   image: redis:7.2.2
  #   container_name: "redis"
  #   volumes:
  #     - ./apps/api/data/redis:/data
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     retries: 3
  #     timeout: 6s
# volumes:
# mongodb: null
# bullmq:
#     driver: bridge
