export default function makeUserService() {
	function signup(provider: 'google' | 'github') {
		// Validate parameters...
		// Create user...
		// Create user items...

		return true;
	}

	function signin(email: string) {
		// Validate parameters...
		// Create user...
		// Create user items...

		return true;
	}

	return Object.freeze({ signup, signin });
}
