export const _REQUEST_TIME_OUT = 3 * 1000;
export const RETRY_INTERVAL = 3 * 1000;
export const MAX_RETRY_TIMES = 3;
export const HEART_BEAT_WAIT_TIME = 5 * 1000;

export const PRIMARY_SOCKET_OPEN_EVENT = 'PRIMARY_SOCKET_OPEN_EVENT';
export const PRIMARY_SOCKET_CLOSE_EVENT = 'PRIMARY_SOCKET_CLOSE_EVENT';
export const PRIMARY_SOCKET_ERROR_EVENT = 'PRIMARY_SOCKET_ERROR_EVENT';
export const PRIMARY_SOCKET_MESSAGE_EVENT = 'PRIMARY_SOCKET_MESSAGE_EVENT';
export const PRIMARY_SOCKET_RECONNECTED_EVENT = 'PRIMARY_SOCKET_RECONNECTED_EVENT';
